# Site settings
title: Your Name - Translator Portfolio
description: Professional translator specializing in [your languages]
baseurl: "" # the subpath of your site, e.g. /blog/
# Replace with your GitHub Pages URL:
# - For user site (repo named username.github.io): https://yourusername.github.io
# - For project site: https://yourusername.github.io/repository-name
url: "https://laurastopiellotraductora.github.io/portfolio/" # Get this from Settings > Pages in your GitHub repo

# User settings
username: Your Name
user_description: Professional Translator
user_title: Translator
email: your.email@example.com
twitter_username: your_twitter
github_username: your_github

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  portfolio:
    output: true

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio" 